
allegro_hello_world: allegro_hello_world.o
	gcc allegro_hello_world.o -o allegro_hello_world

allegro_hello_world.o:
	gcc allegro_hello_world.c -l allegro -l allegro_font -o allegro_hello_world.o

clean:
	rm *.o
