.TH "helper_functions.c" 3 "Sun May 2 2021" "Conway" \" -*- nroff -*-
.ad l
.nh
.SH NAME
helper_functions.c \- Group 7 helper functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'helper_functions\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclear_screen\fP (void)"
.br
.RI "Clears terminal in an OS-specific basis\&. "
.ti -1c
.RI "void \fBflush_stdin\fP (char limit)"
.br
.RI "Flushes the stdin buffer\&. Takes characters from stdin until limit is found\&. "
.in -1c
.SH "Detailed Description"
.PP 
Group 7 helper functions\&. 


.PP
.PP
\fBAuthor\fP
.RS 4
Grupo 7 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void clear_screen (void)"

.PP
Clears terminal in an OS-specific basis\&. 
.SS "void flush_stdin (char limit)"

.PP
Flushes the stdin buffer\&. Takes characters from stdin until limit is found\&. 
.PP
\fBParameters\fP
.RS 4
\fIlimit\fP Character that indicates where to stop flushing 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Conway from the source code\&.
