.TH "main.c" 3 "Sun May 2 2021" "Conway" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- Plays Conway's Game of Life\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'helper_functions\&.h'\fP
.br
\fC#include 'conway\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "Main function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Plays Conway's Game of Life\&. 


.PP
.PP
\fBAuthor\fP
.RS 4
Grupo 7 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Main function\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Conway from the source code\&.
